all:
  vars:
    ansible_ssh_user: matheus
    harbor_admin: cncfdemo
    cert_domain_name: registry.cncf.raj.ninja
    cert_admin_email: test@raj.ninja
  children:
    harbor:
      hosts:
        34.71.192.242